name = "r2-proxy-worker"
main = "functions/api/r2-proxy.js"
compatibility_date = "2024-02-06" # Using current date as compatibility_date

[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "eddwithoutthewar-bucket"
