name = "persona"
compatibility_date = "2024-02-06"

# This declares the main entrypoint of the Worker.
# It tells Cloudflare that this is NOT an assets-only project.
main = "./build/_worker.js"

# This section defines the static assets and creates the `ASSETS`
# binding that our worker script will use to access them.
[assets]
directory = "./build"
binding = "ASSETS"
