name = "persona"
main = "./workers-site/index.js"
compatibility_date = "2024-01-01" # You can update this to a more recent date

[site]
bucket = "./build"

[env.production]
# Add any production-specific environment variables here if needed
